// <auto-generated />
using System;
using Gunluk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104121348_Ilk")]
    partial class Ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1763),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1755)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1785),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1784)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1786),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1786)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1788),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1787)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1789),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1789)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1790),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1790)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1791),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1791)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1793),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1794),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1793)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1795),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1795)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1796),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1796)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1797),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1797)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1799),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1798)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1800),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1799)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1801),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1800)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1802),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1802)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1832),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1832)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1834),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1834)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1835),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1835)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1836),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1836)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1838),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1838)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1839),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1839)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1840),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1840)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1841),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1841)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1842),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1842)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1843),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1843)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1844),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1844)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1845),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1845)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1846),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1846)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1848),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1847)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1849),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1848)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1850),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1849)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1851),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1850)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1852),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1851)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1872),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1872)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1873),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1873)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1874),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1874)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1876),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1875)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1877),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1876)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1878),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1877)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1879),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1879)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1880),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1880)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1881),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1881)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1882),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1882)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1883),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1883)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1884),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1884)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1885),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1885)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1886),
                            Icerik = "\r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat        scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet       ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget   lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut       metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 47, 892, DateTimeKind.Local).AddTicks(1886)
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "İş Dünyam"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Genel"
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.HasOne("Gunluk.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
